/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as ReportLocationRouteImport } from './routes/report.location'
import { Route as ReportQuestionsRouteImport } from './routes/report.questions'
import { Route as ReportReviewRouteImport } from './routes/report.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportRoute,
} as any)
const ReportLocationRoute = ReportLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => ReportRoute,
} as any)
const ReportQuestionsRoute = ReportQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ReportRoute,
} as any)
const ReportReviewRoute = ReportReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ReportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRouteWithChildren
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/report/location': typeof ReportLocationRoute
  '/report/questions': typeof ReportQuestionsRoute
  '/report/review': typeof ReportReviewRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/report/location': typeof ReportLocationRoute
  '/report/questions': typeof ReportQuestionsRoute
  '/report/review': typeof ReportReviewRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRouteWithChildren
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/report/location': typeof ReportLocationRoute
  '/report/questions': typeof ReportQuestionsRoute
  '/report/review': typeof ReportReviewRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/forgot-password'
    | '/profile'
    | '/report'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/report/location'
    | '/report/questions'
    | '/report/review'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/forgot-password'
    | '/profile'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/report/location'
    | '/report/questions'
    | '/report/review'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/forgot-password'
    | '/profile'
    | '/report'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/report/location'
    | '/report/questions'
    | '/report/review'
    | '/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRouteWithChildren
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/location': {
      id: '/report/location'
      path: '/location'
      fullPath: '/report/location'
      preLoaderRoute: typeof ReportLocationRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/questions': {
      id: '/report/questions'
      path: '/questions'
      fullPath: '/report/questions'
      preLoaderRoute: typeof ReportQuestionsRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/review': {
      id: '/report/review'
      path: '/review'
      fullPath: '/report/review'
      preLoaderRoute: typeof ReportReviewRouteImport
      parentRoute: typeof ReportRoute
    }
  }
}

interface ReportRouteChildren {
  ReportLocationRoute: typeof ReportLocationRoute
  ReportQuestionsRoute: typeof ReportQuestionsRoute
  ReportReviewRoute: typeof ReportReviewRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportLocationRoute: ReportLocationRoute,
  ReportQuestionsRoute: ReportQuestionsRoute,
  ReportReviewRoute: ReportReviewRoute,
  ReportIndexRoute: ReportIndexRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRouteWithChildren,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
